import json
from pathlib import Path

import subprocess
import sys

from openai import OpenAI
from utils_exp.config import ExperimentConfig
from utils_LLM.experiments_schema import EXPERIMENTS_SCHEMA

client = OpenAI()


def load_prompt_from_terminal(
    base_prompt_path: str = "utils_LLM/base_prompt.md",
) -> str:
    base_prompt = Path(base_prompt_path).read_text(encoding="utf-8")

    user_prompt = input("\nEnter experiment prompt:\n> ")

    return base_prompt + "\n\n" + user_prompt.strip()


def call_llm(prompt: str, model: str = "gpt-4o-2024-08-06") -> dict:
    response = client.responses.create(
        model=model,
        input=prompt,
        temperature=0,
        text={
            "format": {
                "type": "json_schema",
                "name": EXPERIMENTS_SCHEMA["name"],
                "strict": True,
                "schema": EXPERIMENTS_SCHEMA["schema"],
            }
        },
    )
    return json.loads(response.output_text)


def write_experiments_module(payload: dict, out_path: str = "experiments.py") -> None:
    # Validate that ExperimentConfig can be constructed (catches unknown keys etc.)
    cfgs = [ExperimentConfig(**e) for e in payload["experiments"]]

    for e in payload["experiments"]:
        if isinstance(e["run_spectral"], str):
            e["run_spectral"] = e["run_spectral"].capitalize()

    lines = [
        "# Auto-generated by prompt_llm.py\n",
        "from __future__ import annotations\n\n",
        "from utils_exp.config import ExperimentConfig\n\n",
        "EXPERIMENTS = [\n",
    ]

    # Write only the keys returned by the LLM (keeps file small and explicit)
    for e, _cfg in zip(payload["experiments"], cfgs):
        lines.append("    ExperimentConfig(\n")
        for k, v in e.items():
            lines.append(f"        {k}={repr(v)},\n")
        lines.append("    ),\n\n")

    lines.append("]\n")
    Path(out_path).write_text("".join(lines), encoding="utf-8")


if __name__ == "__main__":
    prompt = load_prompt_from_terminal()
    payload = call_llm(prompt)
    write_experiments_module(payload, "experiments.py")
    subprocess.run([sys.executable, "main.py"], check=True)